modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "humectant"
version = "${version}"
displayName = "Humectant Library"
authors = "throbbingMoist"
description = '''
Humectant Library is a mod which provides several utilities for my mods. It doesn't do much on its' own, but may be required by other mods as a dependency.
'''
#logoFile = ""

[[dependencies.humectant]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.humectant]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.humectant]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "humectant.mixins.json"
